name: Test
on:
  push:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 60
    env:
      ESVU_PATH: ${{ github.workspace }}
    steps:
      - uses: actions/setup-node@v4
      - name: Test LibJS
        run: |
          npm i -g esvu
          esvu install libjs
          ./bin/ladybird-js
